apiVersion: v1
kind: Service
metadata:
  name: aether-registrar
  namespace: aether-system
  labels:
    app: aether-registrar
    app.kubernetes.io/name: aether-registrar
spec:
  clusterIP: None
  selector:
    app: aether-registrar
    app.kubernetes.io/name: aether-registrar
  ports:
    - name: grpc
      appProtocol: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
  type: ClusterIP
