admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
    - name: outbound_http_svc_0
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 18081
          network_namespace_filepath: "/host/run/netns/99cca569ea1f"
      traffic_direction: OUTBOUND
      filter_chains:
        - filters:
            - name: envoy.filters.network.set_filter_state
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.set_filter_state.v3.Config
                on_new_connection:
                  - object_key: aether.network.network_namespace
                    format_string:
                      text_format_source:
                        inline_string: '%FILTER_STATE(envoy.network.network_namespace:PLAIN)%'
                    shared_with_upstream: ONCE
                    factory_key: envoy.string
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: outbound_http_svc_0
                codec_type: AUTO
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                      log_format:
                        text_format_source:
                          inline_string: |
                            SVC-0 [%START_TIME%] "%REQUEST_HEADER(:METHOD)% %REQUEST_HEADER(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESPONSE_HEADER(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQUEST_HEADER(X-FORWARDED-FOR)%" "%REQUEST_HEADER(USER-AGENT)%" "%REQUEST_HEADER(X-REQUEST-ID)%" "%REQUEST_HEADER(:AUTHORITY)%" "%UPSTREAM_HOST%" "%UPSTREAM_CLUSTER%" E:"%FILTER_STATE(envoy.network.network_namespace:PLAIN)%" A:"%FILTER_STATE(aether.network.network_namespace:PLAIN)%"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                      upstream_log:
                        - name: envoy.access_loggers.stdout
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                            log_format:
                              text_format_source:
                                inline_string: |
                                  SVC-0 [%START_TIME%] "%REQUEST_HEADER(:METHOD)% %REQUEST_HEADER(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESPONSE_HEADER(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQUEST_HEADER(X-FORWARDED-FOR)%" "%REQUEST_HEADER(USER-AGENT)%" "%REQUEST_HEADER(X-REQUEST-ID)%" "%REQUEST_HEADER(:AUTHORITY)%" "%UPSTREAM_HOST%" "%UPSTREAM_CLUSTER%" E:"%UPSTREAM_FILTER_STATE(envoy.network.network_namespace:PLAIN)%" UP_E:"%UPSTREAM_FILTER_STATE(envoy.network.network_namespace:PLAIN)%" UP_A:"%UPSTREAM_FILTER_STATE(aether.network.network_namespace:PLAIN)%"
                route_config:
                  name: svc_2
                  virtual_hosts:
                    - name: svc_2
                      domains: [ "svc-2" ]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: svc_2

  clusters:
    - name: svc_2
      type: LOGICAL_DNS
      load_assignment:
        cluster_name: svc_2
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: svc-2
                      port_value: 18080
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      transport_socket_matcher:
        matcher_tree:
          input:
            name: envoy.matching.inputs.filter_state
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.transport_socket.v3.FilterStateInput
              key: aether.network.network_namespace
          exact_match_map:
            map:
              "/host/run/netns/99cca569ea1f":
                action:
                  name: envoy.matching.action.transport_socket.name
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.transport_socket.v3.TransportSocketNameAction
                    name: svc_0_socket
              "/host/run/netns/00b4a7e976cf":
                action:
                  name: envoy.matching.action.transport_socket.name
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.transport_socket.v3.TransportSocketNameAction
                    name: svc_1_socket
        on_no_match:
          action:
            name: envoy.matching.action.transport_socket.name
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.transport_socket.v3.TransportSocketNameAction
              name: svc_3_socket
      transport_socket_matches:
        - name: svc_0_socket
          match: {}
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /var/lib/certs/svc-0.crt
                    private_key:
                      filename: /var/lib/certs/svc-0.key
                validation_context:
                  trusted_ca:
                    filename: /var/lib/certs/ca.crt

        - name: svc_1_socket
          match: {}
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /var/lib/certs/svc-1.crt
                    private_key:
                      filename: /var/lib/certs/svc-1.key
                validation_context:
                  trusted_ca:
                    filename: /var/lib/certs/ca.crt

        - name: svc_3_socket
          match: {}
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /var/lib/certs/svc-3.crt
                    private_key:
                      filename: /var/lib/certs/svc-3.key
                validation_context:
                  trusted_ca:
                    filename: /var/lib/certs/ca.crt
