admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
    - name: inbound_http_svc_2
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18080
          network_namespace_filepath: "/host/run/netns/d7b60a7e79e3"
      traffic_direction: INBOUND
      listener_filters:
        - name: "envoy.filters.listener.tls_inspector"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http_svc_2
                codec_type: AUTO
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                      log_format:
                        text_format_source:
                          inline_string: |
                            SVC-2 [%START_TIME%] "%REQUEST_HEADER(:METHOD)% %REQUEST_HEADER(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESPONSE_HEADER(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQUEST_HEADER(X-FORWARDED-FOR)%" "%REQUEST_HEADER(USER-AGENT)%" "%REQUEST_HEADER(X-REQUEST-ID)%" "%REQUEST_HEADER(:AUTHORITY)%" "%UPSTREAM_HOST%" E:"%FILTER_STATE(envoy.network.network_namespace:PLAIN)%" A:"%FILTER_STATE(aether.network.network_namespace:PLAIN)%"
                forward_client_cert_details: SANITIZE_SET
                set_current_client_cert_details:
                  subject: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_svc_2
                  virtual_hosts:
                    - name: local_svc_2
                      domains: [ "*" ]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_svc_2
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              require_client_certificate: true
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /var/lib/certs/svc-2.crt
                    private_key:
                      filename: /var/lib/certs/svc-2.key
                validation_context:
                  trusted_ca:
                    filename: /var/lib/certs/ca.crt

    - name: inbound_http_svc_3
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18080
          network_namespace_filepath: "/host/run/netns/1fb499d47f74"
      traffic_direction: INBOUND
      listener_filters:
        - name: "envoy.filters.listener.tls_inspector"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      filter_chains:
        - filters:
            - name: envoy.filters.network.set_filter_state
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.set_filter_state.v3.Config
                on_new_connection:
                  - object_key: aether.network.network_namespace
                    format_string:
                      text_format_source:
                        inline_string: '%FILTER_STATE(envoy.network.network_namespace:PLAIN)%'
                    shared_with_upstream: ONCE
                    factory_key: envoy.string
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http_svc_3
                codec_type: AUTO
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                      log_format:
                        text_format_source:
                          inline_string: |
                            SVC-3 [%START_TIME%] "%REQUEST_HEADER(:METHOD)% %REQUEST_HEADER(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESPONSE_HEADER(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQUEST_HEADER(X-FORWARDED-FOR)%" "%REQUEST_HEADER(USER-AGENT)%" "%REQUEST_HEADER(X-REQUEST-ID)%" "%REQUEST_HEADER(:AUTHORITY)%" "%UPSTREAM_HOST%" E:"%FILTER_STATE(envoy.network.network_namespace:PLAIN)%" A:"%FILTER_STATE(aether.network.network_namespace:PLAIN)%"
                forward_client_cert_details: SANITIZE_SET
                set_current_client_cert_details:
                  subject: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_svc_3
                  virtual_hosts:
                    - name: local_svc_3
                      domains: [ "*" ]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_svc_2
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              require_client_certificate: true
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /var/lib/certs/svc-3.crt
                    private_key:
                      filename: /var/lib/certs/svc-3.key
                validation_context:
                  trusted_ca:
                    filename: /var/lib/certs/ca.crt

  clusters:
    - name: local_svc_2
      type: STATIC
      load_assignment:
        cluster_name: local_svc_2
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8091
      upstream_bind_config:
        source_address:
          address: 127.0.0.1
          port_value: 0
          network_namespace_filepath: "/host/run/netns/d7b60a7e79e3"
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
    - name: local_svc_3
      type: STATIC
      load_assignment:
        cluster_name: local_svc_3
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8093
      upstream_bind_config:
        source_address:
          address: 127.0.0.1
          port_value: 0
          network_namespace_filepath: "/host/run/netns/1fb499d47f74"
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
